[Gate]
address = "192.168.1.1/24"
port = 443
pool = "192.168.1.1/24"
private_key = "Rz6EHuDj3NUih/QORBAJ+swtUaZnYsUAA0JOcuc/lT8="

[[SecurityGroup]]
name = "group1"
allowed_ip = ["192.168.1.2/24"]

[[SecurityGroup]]
name = "group2"
allowed_ip = ["192.168.1.3/24", "10.155.10.16"]

[[User]]
name = "user1"
ip = "192.168.0.1"
public_key = "Rz6EHuDj3NUih/QORBAJ+swtUaZnYsUAA0JOcuc/lT8="
security_group = ["group1"]

[[User]]
name = "user2"
ip = "192.168.0.2"
public_key = "Rz6EHuDj3NUih/QORBAJ+swtUaZnYsUAA0JOcuc/lT8="
security_group = ["group1", "group2"]